### PR TITLE
Less logs from scheduler

### PR DESCRIPTION
**Pull request by kris6673**

### CODE REVIEW

**Comment by KelvinTegelaar** [comment]
We still want normal scheduled tasks to get logged, how about an if that decides the debug level?

**Comment by kris6673** [comment]
Used the if statement that was in there, that already checked if it was an alert
should do it i think

**Comment by kris6673** [comment]
if you merge this, please squash merge it to hide my shameful commits q.q

**Comment by KelvinTegelaar** [comment]
this was fixed by John, so closing as it conflicts, but thanks Bobby!

**Pull request closed without merging**
