### PR TITLE
Updated Anti-Phishing Policy Standards for more granular configuration

### PR DESCRIPTION
**Pull request by kakaiwa**
https://github.com/KelvinTegelaar/CIPP/issues/2593

### CODE REVIEW

**Comment by KelvinTegelaar** [comment]
Please see https://github.com/KelvinTegelaar/CIPP-API/pull/687#issuecomment-2017741657

**Comment by kakaiwa** [comment]
@KelvinTegelaar Thank you very much for the feedback. I based the default value for these parameters based on the default value that is set when creating a custom policy in Powershell:
https://learn.microsoft.com/en-us/powershell/module/exchange/new-antiphishpolicy?view=exchange-ps

Even without the options I added, the newly created policy uses these default values, so I believe it's not less secure. However, I agree that making the default values as secure as possible is important. If you’d like, I can set the default values for these parameters as below. Please let me know your thoughts on this. Thank you in advance.
- AuthenticationFailAction: Quarantine
- SpoofQuarantineTag: AdminOnlyAccessPolicy
- TargetedUserQuarantineTag: AdminOnlyAccessPolicy
- TargetedDomainQuarantineTag: AdminOnlyAccessPolicy

**Comment by KelvinTegelaar** [comment]
Sounds good! If you do that, we'll merge.

**Comment by kakaiwa** [comment]
@KelvinTegelaar Thank you for the response. I have updated standards.json so that the first values are set to the above. I would appreciate it f you could merge at your earliest convenience. Thank you in advance.

**Pull request merged**
